### ISSUE TITLE
Raspberry Pi 4B - Interfaces/WiFi and Luci

### ISSUE THREAD

**Issue by truefriend-cz** [SuLingGG/OpenWrt-Rpi#42]
Hi, how i can access to Wifi after clean install and Luci?

After clean your firmware openwrt-bcm27xx-bcm2711-rpi-4-squashfs-sysupgrade.img.zip (Lean 5.4 - build: 12.11.2020):

1.
```
opkg update
opkg install luci
opkg install luci-ssl
opkg install luci-i18n-base-en
/etc/init.d/uhttpd restart
```
2. open Luci webpage
3. going to Network - Interfaces
ended with error:
```
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute arcombine dispatcher target for entry '/admin/network/network'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/network/proto_4x6.lua:61: attempt to call method 'register_error_code' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
```
3. going to Network - Wireless
ended with error:
```
/usr/lib/lua/luci/model/network/proto_4x6.lua:61: attempt to call method 'register_error_code' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/network/proto_4x6.lua:61: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/model/network.lua:1704: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/admin/network.lua:70: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:572: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:238: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
```

How i can fix?

Thanks

**Comment by SuLingGG** [comment]
First of all, my OpenWrt firmware is different from offical OpenWrt firmware.

On offical OpenWrt's snapshots firmware, LuCI is not pre-installed. If you want to use LuCI to control OpenWrt, you must connect to ssh then install LuCI and other modules, after that, you can use LuCI normally.

But as for my OpenWrt firmware, LuCI and other modules are pre-installed at the firmware. All of you will do is:

1. Flash firmware
2. Power on the raspberrypi
3. Search the wireless point that named "OpenWrt" and connect
4. Use http://192.168.1.1 to visit LuCI control panel
5. Use username: root, password: password to login in LuCI

If you use "opkg" install LuCI and other modules by SSH after a new flash, some modles will conflict and they will not works correctly, because opkg use offical opkg software source and install offical packages, but my firmware use 3rd source to build, so use offical opkg packages source will cause unpredictable problems.

Such as https://github.com/SuLingGG/OpenWrt-Rpi/issues/43 . This problem will not happened with firmware-based LuCI, on firmware-based LuCI, we can change the uhttpd port correctly and it will take effect after a reboot (or service uhttpd restart).

Maybe you shoud have a new flash to use my firmware, and during the using time, try not to use opkg to install packages.

Have a good time~
