### ISSUE TITLE
WiFi encryption AP problem

### ISSUE THREAD

**Issue by truefriend-cz** [SuLingGG/OpenWrt-Rpi#44]
When I turn on WiFi encryption like this:
WPA/WPA2 PSK (TKIP, CCMP)

It will appear on my device (smartphone) as follows:
[WPA-PSK-CCMP+TKIP][ESS]

Tested on openwrt-bcm27xx-bcm2711-rpi-4-squashfs-sysupgrade.img (2020-11-13), Original and Lean.

For example from others...
If this same settings on AP by Mikrotik (RouterOS) show encryption on smartphone as:
[WPA2-PSK-CCMP+TKIP][RSN-PSK-CCMP+TKIP][WPA-PSK-CCMP+TKIP][ESS]

**Comment by SuLingGG** [comment]
My job is compiling the firmware, maybe this problem is caused by source code. If you are concern at this problem, please make issues to upstream. For example, if you use Lean's firmware, you can make issues to <https://github.com/coolsnowwolf/lede>

But I think this problem is not very important, if it does not affect the use, you can ignore it...
